# Use the latest Ubuntu 20.04 LTS
dist: focal
# Uncomment the addons section to use MongoDB 4.4
#addons:
#  apt:
#    sources:
#    - sourceline: 'deb https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/4.4 multiverse'
#      key_url: 'https://www.mongodb.org/static/pgp/server-4.4.asc'
################################################################

# Set language support to JavaScript / NodeJS
language: node_js

# sudo privileges are not needed
sudo: false

# Enable MySQL or MongoDB service
services:
#  - mysql
#  - mongodb

# Test against both the supported and latest LTS versions of NodeJS
# Current versions move too quickly, so we don't bother with these in the CI/CD
node_js:
  - lts/*
  - 14
  - 12

# install NPM packages from the package.lock file
install:
  - npm install

# run required scripts before the build process starts
script:
  - npm run lint
  - npm test

# Branch blocklist - These branches won't trigger a build.
branches:
  except:
  - experimental

# Branch safelist - These branches will trigger a build.
branches:
  only:
  - main
  - develop # Triggers builds on the develop branch 
  - /^(release)-\d+\.\d+(\.\d+)?(-\S*)?$/ # Triggers a build on release-x.x.x branches.
#  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # Triggers a build on vX.X.X tags.